INSERT INTO provinces VALUES
("Abra", null),
("Agusan del Norte", null),
("Agusan del Sur", null),
("Aklan", null),
("Albay", null),
("Antique", null),
("Apayao", null),
("Aurora", null),
("Basilan", null),
("Bataan", null),
("Batanes", null),
("Batangas", null),
("Benguet", null),
("Biliran", null),
("Bohol", null),
("Bukidnon", null),
("Bulacan", null),
("Cagayan", null),
("Camarines Norte", null),
("Camarines Sur", null),
("Camiguin", null),
("Capiz", null),
("Catanduanes", null),
("Cavite", null),
("Cebu", null),
("Compostela Valley", null),
("Davao del Norte", null),
("Davao del Sur", null),
("Davao Oriental", null),
("Dinagat Islands", null),
("Eastern Samar", null),
("Guimaras", null),
("Ifugao", null),
("Ilocos Norte", null),
("Ilocos Sur", null),
("Iloilo", null),
("Isabela", null),
("Kalinga", null),
("La Union", null),
("Laguna", null),
("Lanao del Norte", null),
("Lanao del Sur", null),
("Leyte", null),
("Maguindanao", null),
("Marinduque", null),
("Masbate", null),
("Metropolitan Manila", null),
("Misamis Occidental", null),
("Misamis Oriental", null),
("Mountain Province", null),
("Negros Occidental", null),
("Negros Oriental", null),
("North Cotabato", null),
("Northern Samar", null),
("Nueva Ecija", null),
("Nueva Vizcaya", null),
("Occidental Mindoro", null),
("Oriental Mindoro", null),
("Palawan", null),
("Pampanga", null),
("Pangasinan", null),
("Quezon", null),
("Quirino", null),
("Rizal", null),
("Romblon", null),
("Samar", null), 
("Sarangani", null),
("Shariff Kabunsuan", null),
("Siquijor", null),
("Sorsogon", null),
("South Cotabato", null),
("Southern Leyte", null),
("Sultan Kudarat", null),
("Sulu", null),
("Surigao Del Norte", null),
("Surigao Del Sur", null),
("Tarlac", null),
("Tawi-Tawi", null),
("Zambales", null),
("Zamboanga del Norte", null),
("Zamboanga del Sur", null),
("Zamboanga Sibugay", null);